version: '3.8'

services:
  sherlog-mcp:
    image: sherlog-mcp-android
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-http://localhost:8000/auth/google/callback}
      - OAUTH_ENCRYPTION_KEY=${OAUTH_ENCRYPTION_KEY}
      - EXTERNAL_MCPS_JSON=${EXTERNAL_MCPS_JSON}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gh-config:/root/.config/gh
      - aws-config:/root/.aws
      - gcloud-config:/root/.config/gcloud
      - browserstack-config:/root/.browserstack-cli.yaml
      - mcp-data:/app/data

volumes:
  gh-config:
  aws-config:
  gcloud-config:
  browserstack-config:
  mcp-data: